### PR TITLE
Fix Circle CI doc build CI

### LINKED ISSUE #56: Fix Circle doc build CI
Error msg:
```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Cloning git repository

error cloning repository: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

### PR DESCRIPTION
**Pull request by AtsushiSakai**
fix #56

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
GitHub deploy key was removed... This post helps me: https://inokara.hateblo.jp/entry/2020/06/30/000345

**Comment by AtsushiSakai** [comment]
Hm.. scipy build failed..

```
) <class 'ImportError'>
ImportError("/usr/local/julia/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-310-x86_64-linux-gnu.so)")
  File "/root/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 413, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/root/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_linprog.py", line 21, in <module>
    from ._linprog_highs import _linprog_highs
  File "/root/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_linprog_highs.py", line 20, in <module>
    from ._highs._highs_wrapper import _highs_wrapper
```

**Comment by terasakisatoshi** [comment]
> Hm.. scipy build failed..
> 
> ```
> ) <class 'ImportError'>
> ImportError("/usr/local/julia/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-310-x86_64-linux-gnu.so)")
>   File "/root/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 413, in <module>
>     from ._linprog import linprog, linprog_verbose_callback
>   File "/root/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_linprog.py", line 21, in <module>
>     from ._linprog_highs import _linprog_highs
>   File "/root/.julia/conda/3/lib/python3.10/site-packages/scipy/optimize/_linprog_highs.py", line 20, in <module>
>     from ._highs._highs_wrapper import _highs_wrapper
> ```

FYI 
https://github.com/JuliaPy/PyCall.jl/issues/990#issuecomment-1224878410

**Comment by AtsushiSakai** [comment]
Maybe  related: https://github.com/scipy/scipy/issues/17070

**Pull request merged**
